### ISSUE TITLE
Email contact ?

### ISSUE THREAD

**Issue by axel3rd** [GroupePSA/titan-project#1]
Hello,

In [FAQ - Are my data safe](https://github.com/GroupePSA/titan-project/blob/master/README.md#are-my-data-safe-), email contact is `mail.com`. Is it true ? Or `gmail.com` ?

**Comment by Transrian** [comment]
@axel3rd Yes it's true, didn't miswrote it

**Comment by axel3rd** [comment]
Ah ok sorry 😕, I didn't know this email domain.
