### ISSUE TITLE
Build process : link SonarCloud analysis

### ISSUE THREAD

**Issue by axel3rd** [GroupePSA/titan-project#2]
It could be nice if SonarCloud analysis would be enabled on build process (*push* code event).

I know having some unit tests could be hard due to architecture execution, but quality analysis is always a value added 😁.

The SonarCloud badge would be beautiful at top of `README.md`, and one project on https://sonarcloud.io/organizations/psa/projects is not enough !

[SonarCloud GitHub Action](https://github.com/marketplace/actions/sonarcloud-scan) seems great for that. I can help for that.

**Comment by Transrian** [comment]
Totally agree on that, even if I though about Travis (for tests), as I'm more use of this one :)

But why not SonarCloud, one repo at that time is not enough like you said ;)

Agree that it will not be funny to make the tests: I see *3* distrincts zones to tests :
- **Frontend**: Due to the choice I had to do to use Jquery, there's no npm for it, all the dependencies are *badly* stored in the [/frontend/js](https://github.com/GroupePSA/titan-project/tree/master/frontend/js) directory .. And there's no tests at this time, do you know if it would be possible to test something like that ?
- **Logstash**: Stored in the [/logstatsh](https://github.com/GroupePSA/titan-project/tree/master/logstash) directory, we need to build them (docker-compose) to test the backend, + build shoud work with some variations based on the parameters listed [here](https://github.com/GroupePSA/titan-project/wiki/Custom-Logstash-instance)
- **Backend**: Classical node / express backend, all API url & req are tested, no unitary test yet -> problematic is we need to have a local (*for now*) Docker where the logstash image are built

Do you think all of that would be possible with SonarCloud (backend at least, front is less important for me atm) ?

&#43; Later, once I did some cleaning of the frontend, we'll need to build Docker image & push them in a repository (https://hub.docker.com ?) for : 
- Frontend
- Backend
- Lots of Logstash images ..

**Comment by axel3rd** [comment]
SonarCloud is just a static code analyser, it is not directly linked with tests execution.
If build can execute tests, Sonar[Cloud|Qube] can use the output report to calculate code coverage (see [Test Coverage & Execution](https://docs.sonarqube.org/latest/analysis/coverage/) for framework supported).

If no tests can be executed, [SonarCloud GitHub action](https://github.com/marketplace/actions/sonarcloud-scan) would be the most simple.
If tests can be executed with Travis [Using Docker in Builds](https://docs.travis-ci.com/user/docker/), [SonarCloud Travis integration](https://docs.travis-ci.com/user/sonarcloud/) should be used.

But starting some previous Docker container and executing some "remote on localhost" tests are most "integration tests". I don't know if code coverage could be used in this case.

The JavaScript code coverage use case is more unit tests with [jtest](https://jestjs.io/) & [nock](https://github.com/nock/nock) (for sample).
But I'm agree, mocking *logstash* is perhaps not easy.

**In a short term, I think SonarCloud analysis could be started without tests**, let me know if you are agree with that.

----

> Due to the choice I had to do to use Jquery, there's no npm for it, all the dependencies are badly stored in the /frontend/js directory

Not sure to understand ... [NPM frontend-dependencies](https://www.npmjs.com/package/frontend-dependencies) or [Yarn](https://yarnpkg.com/) would be not a solution for that ? 

BTW, for SonarCloud, these kind of thirdpart/vendor libraries could be excluded.

----

> Later, once I did some cleaning of the frontend, we'll need to build Docker image & push them in a repository (https://hub.docker.com ?)

Yes, why not, more easiest way for some others to use *titan-project*.

----

Nothing to see, but you may have many concurrency on this project due to its name: https://en.wikipedia.org/wiki/Project_Titan

**Comment by Transrian** [comment]
Didn't wanted to close that ..

**Comment by axel3rd** [comment]
About SonarCloud exclusions, add in `sonar-project.properties`:
```
sonar.exclusions=frontend/js/bootstrap*,something/else
```

But it requires project knowledge about *imported vs implemented* files 😭

**Comment by Transrian** [comment]
To start, seems like I missunderstand usage of SonarCloud, your PR was welcome, though it was too for do some tests ..
I'll be checking to see in details SonarCloud details once I got some sleep, for result seems very strange for me at this time .. Results are *too* good ?

> The JavaScript code coverage use case is more unit tests with jtest & nock (for sample).
> But I'm agree, mocking logstash is perhaps not easy.

Don't think it will be possible yeah ..

> Not sure to understand ... NPM frontend-dependencies or Yarn would be not a solution for that ?

Didn't know the first, and didn't though about the second, thank you very much, yeah that's definitly the way to go :D

> Nothing to see, but you may have many concurrency on this project due to its name: 
> https://en.wikipedia.org/wiki/Project_Titan

Except about the Apple project, don't think it would be a problem, am I wrong ?

> But it requires project knowledge about imported vs implemented files
For back no imports, for frontend I think 

`sonar.exclusions=frontend/js/*.js,frontend/js/ace-min-noconflict/*`
(basically anything except js/custom)
Do you want to give it a try ? :)

**Comment by Transrian** [comment]
About the Travis part, I'm pretty used to it, so yeah that's the way to go I think, but didn't catch the reason of the SonarCloud into Travis integration ?

**Comment by axel3rd** [comment]
> SonarCloud [...] Results are too good ?

The Quality Gate only display issues "on new code" ([Water Leak concept](https://docs.sonarqube.org/latest/user-guide/fixing-the-water-leak/)) => first analysis is not the "global true".

But for a first analysis, it is not too bad 👍 (https://sonarcloud.io/dashboard?id=org.psa%3Atitan-project).

----

> Don't think it will be possible yeah ..

About jtest & nock, I could give you some link on simple JS app (internally : The GitHub probot for PSA CI documentation ... simply foundable in our PSA GitHub 😁).

----

> [frontend dependencies] yeah that's definitly the way to go :D

Never try *frontend-dependencies*, but perhaps more simple to use an external tools like Yarn for "basics" usages (another tool was `bower`, but dead).

--- 

> [Titan project name] Except about the Apple project, don't think it would be a problem, am I wrong ?

[Blizzard Titan project](http://www.jeuxvideo.com/news/476151/blizzard-avec-project-titan-nous-avons-echoue-lamentablement.htm) is dead, so your are right ^^.

It was initially a joke 😂. But if this project grows and become massively used, this kind of problem can come  ⚠️. 

---

> (basically anything except js/custom) Do you want to give it a try ? :)

I'm going @home, IDE closed ... but just with GitHub edition, why not !

**Comment by Transrian** [comment]
> The Quality Gate only display issues "on new code"

Oh ok, seem's more legit 


> Don't think it will be possible yeah ..

For now, it could probably be (don't use a proper library fom now, I just migrated for the live instance from raw exec to docker so we got some things like [that](https://github.com/GroupePSA/titan-project/blob/d47b12a49f156554d4b33651034d0d323824921e/backend/routes/logstash.js#L175) ...., don't judge me too harsh). But once the library set-up ([this one](https://github.com/apocas/dockerode) seem's pretty good), don't know if it would be easy

> The GitHub probot for PSA CI documentation

Perfect, will give it a look as soon as I can :+1: 

> perhaps more simple to use an external tools like Yarn for "basics" usages

Make sense, until a full redesign of front with proper techno, but not plan yet

> It was initially a joke 

Look like I really need to sleep :crying_cat_face: 

> But if this project grows and become massively used

Don't know if massively is the term, as the public scope is very restricted ; but as we already are more than 10 to use it daily in internal, I hope it still will interest others people :smile: 

> I'm going @home, IDE closed ... but just with GitHub edition, why not !

As you wish, I will not work on this until the we, I'm pretty busy those times :disappointed:

**Comment by axel3rd** [comment]
> don't judge me too harsh

Never ! This project is already very nice ! (SonarCloud green analysis, integration tests, ...), it is just to share/promote best practices in software development.

> As you wish, I will not work on this until the we, I'm pretty busy those times 😞

No rush, it is just having these kind of concept in mind, to ensure sustainable project on long life.
And if you are using [SonarLint](https://www.sonarlint.org/) in your favorite IDE, it is more simple and quick magic ✔️.

I will allow me to open separate issues for dedicated (previous) subjects 😁, and this issue could be closed IMO 👍.

**Comment by Transrian** [comment]
Wb @axel3rd,

I set-up the Travis tests for integrations tests -> work well :smile: 

However, for the others tests + tests coverage (that is zero percent and make this repo become red :cry:), I need to set-up the SonarCloud configuration into the [.travis.yml](https://github.com/GroupePSA/titan-project/blob/933b7256aff7945359442d797d55548dfa32e6ee/.travis.yml#L10-L12) file, what I did.

I used my own SonarKey, but here is the [result of the job](https://travis-ci.org/GroupePSA/titan-project/jobs/619185035) :

```
ERROR: Error during SonarQube Scanner execution
ERROR: You're not authorized to run analysis. Please contact the project administrator.
```

Do I have the **Execute Analysys** option enable into the SonarCloud repository configuration (Project -> Administration -> Permissions) ? At first guess, think that's something like that.


&#43; from what I understood, you will need to disable the *action* for SonarCloud embedded into Github so they don't collide with those on Travis, once those are working ?

**Comment by axel3rd** [comment]
Hi @Transrian,

> Do I have the Execute Analysys option enable into the SonarCloud repository configuration (Project -> Administration -> Permissions) ? At first guess, think that's something like that.

I have removed all my tokens for Titan project and I have **added you as owner** of [SonarCloud PSA organization](https://sonarcloud.io/organizations/psa/members) => should be better now.

> + from what I understood, you will need to disable the action for SonarCloud embedded into Github so they don't collide with those on Travis, once those are working ?

[.github/workflows/build.yml](https://github.com/GroupePSA/titan-project/blob/master/.github/workflows/build.yml) file should be deleted in this case, useless.

**Comment by Transrian** [comment]
Even if not perfect at this time, everything work great, and SonarCloud integration is a success, I close this issue
