### ISSUE TITLE
Build process : Enforce PR analysis for any rebase/merge

### ISSUE THREAD

**Issue by axel3rd** [GroupePSA/titan-project#6]
Following #2 

----

Now some checks are enabled on Pull Request (like SonarCloud analysis).
A good practice is to add some [protection branch](https://help.github.com/en/github/administering-a-repository/about-protected-branches) (at min on `master`) to enfore some [checks](https://help.github.com/en/github/administering-a-repository/about-required-status-checks).

With that, no rebase/merge in `master` without some automated checks (unit tests, code quality, ...).

**Comment by Transrian** [comment]
I set-up that (for now, I didn't enforce SonarCube code coverage until the fontend-testing start to be ok agin).
Do you see any others options to enable ?

**Comment by axel3rd** [comment]
> SonarCube

Sonar**Q**ube 😁, and internet hosting is SonarCloud.

>  Do you see any others options to enable ?

I'm not sure sure sure, but the GitHub check enforces only the execution (=> good point).
You can rebase/merge the PR even if SonarCloud analysis is red.

**Comment by Transrian** [comment]
> SonarQube :grin: , and internet hosting is SonarCloud.

:sweat_smile:

> GitHub check enforces only the execution

That's the only I set-up by default (continuous-integration/travis-ci), I deliberately disabled *SonarCloud Trigger* & *SonarCloud Code Analysis* for now.

We will need to test-it once coverage is green again, even if I think that those two are related to the [flow](https://github.com/GroupePSA/titan-project/commit/608b85692cbb8ca6b87652de8063973cd784c647) you set-up at the start using Github Actions.

Or at worst, if that's something we really require, there is *perhaps?* a way to make the [sonnar-scanner](https://github.com/GroupePSA/titan-project/blob/8cc41ed8b3aa29ce4c833fd51eb3cab144a8a0b2/.travis.yml#L23) return status code different than zero on regressions ? Pretty dirty, but if no others ways work .. :imp:

**Comment by axel3rd** [comment]
> We will need to test-it once coverage is green again, even if I think that those two are related to the flow you set-up at the start using Github Actions.

You're right. But checking *checks* of last PR [#8](https://github.com/GroupePSA/titan-project/pull/8/checks), the check is named **SonarCloud Code Analysis**.

> Or at worst, if that's something we really require, there is perhaps? a way to make the sonnar-scanner return status code different than zero on regressions ? Pretty dirty, but if no others ways work .. 👿

When *sonar-scanner* crashes (bad configuration, bug, ...) this is the Travis build which fails.
If you enforce *SonarCloud Code Analysis* check and you can't rebase/merge a PR, remove the check in GitHub branch protection, it will work (already try on some other checks).

**Comment by Transrian** [comment]
Ok, then we'll try and see.
I'll close this issue.
