### ISSUE TITLE
Build process : Add unit tests (in addition of integration tests)

### ISSUE THREAD

**Issue by axel3rd** [GroupePSA/titan-project#7]
Following #2 

----

Integration tests ([currently](https://github.com/GroupePSA/titan-project/blob/d47b12a49f156554d4b33651034d0d323824921e/backend/routes/logstash.js#L175)) are nice, but a good practice is to have unit tests to ensure automatic checks on any code contribution (with code coverage, ...).

Project architecture is quite complex (*logstash* endpoint could be required), but perhaps some mocking solution could help. Sample : [jtest](https://jestjs.io/) & [nock](https://github.com/nock/nock).

[dockerode](https://github.com/apocas/dockerode) could perhaps help.

**Comment by Transrian** [comment]
Tests for backend were partially implemented in #9, and cover most of uses-cases.
However, at that time, there is no proper way to add test for frontend, as it's some basic Jquery. Is tried with jtest, nock, mocha, and some others, and I'm not seing any way of doing that at that time.

What i'm willing to do in short term is to disable tests for frontend -> coverage is the only reason this project is red at that time. Once the frontend rebuild using proper techno, I'll enable them again, so we're clean. However, that may take some times.

Don't really like the idea, but see no others solutions short term. What are your though about it ?

**Comment by axel3rd** [comment]
> Don't really like the idea, but see no others solutions short term. What are your though about it ?

I'm not a fronted development specialist ... but if current architecture is hard to test, yes could be excluded.

`sonar.coverage.exclusions`  property could be used for that in [sonar-project.properties](https://github.com/GroupePSA/titan-project/blob/master/sonar-project.properties).

**Comment by Transrian** [comment]
Oh my god, seeing some green again make me really happy :smiley: 

Even if it's *temporary*, 93% coverage is not too bad, for a product (still) based on cli :laughing: 

Thanks again for your help, I'll keep you inform on next(s) big steps !

**Comment by axel3rd** [comment]
Nice ! A next challenge is doing the same for internal company projects with our quite same tools 😁. 
And promote theses practices around you 👍
